### ISSUE TITLE
Create starship config file

### ISSUE THREAD

**Issue by jladdjr** [jladdjr/bootstrap#113]
Would like to show battery status at 30% for example.

https://starship.rs/config/#battery

In `~/.config/starship.toml`:

```toml
[[battery.display]]
threshold = 50
```

"Always keep your tank half-full"
