### ISSUE TITLE
Notify when production Tower (in ec2) comes up

### ISSUE THREAD

**Issue by jladdjr** [jladdjr/bootstrap#34]
Related: https://github.com/jladdjr/bootstrap/issues/33

Could use something like:
`$ cat prod-tower-health-check.yml`
```
- hosts: all
  tasks:
  - ec2_instance_facts:
      region: 'us-east-1'
      filters:
        "tag:Name": "*{{ instance_name }}*"
    register: ec2_instance_facts
    until: ec2_instance_facts.instances is defined and ec2_instance_facts.instances|length > 0
    retries: 30
    delay: 30

  - set_fact:
      tower_ip: "{{ ec2_instance_facts.instances[0].public_ip_address }}"
      tower_name: "{{ ec2_instance_facts.instances[0].tags.Name }}"

  - shell: notify "Found {{ tower_name }}"

  - get_url:
      url: "https://{{ tower_ip }}/api/login/"
      dest: /tmp/tower_health_check
      validate_certs: no
      force: yes
    register: get_url
    until: '"failed" not in get_url.msg and get_url.status_code == 200'
    retries: 180
    delay: 30
    ignore_errors: yes

  - shell: notify "{{ tower_name }} {{ 'failed to come up.. ಥ益ಥ' if get_url.failed else 'is up!' }}"

  - block:
    - pause:
        seconds: 3

    - shell: notify "The address is {{ tower_ip }}"
      when: not get_url.failed

    - lineinfile:
        create: yes
        line: "{{ tower_name }}:\t\t{{ tower_ip }}"
        insertafter: EOF
        state: present
        path: ~/tower_instances
    when: not get_url.failed
```

with:
`$ cat inventory`
```
[local]
localhost ansible_connection=local ansible_python_interpreter='/usr/bin/env python'
```

`$ cat wait_for_tower`
```
#!/bin/bash

source /usr/bin/virtualenvwrapper.sh
workon ansible-devel
source /home/vagrant/git/ansible-devel/hacking/env-setup > /dev/null 2>&1

ansible-playbook -i /home/vagrant/git/bootstrap/inventory -e instance_name=$1 /home/vagrant/git/bootstrap/prod-tower-health-check.yml
```

You could then run a command like:
`$ nohup wait_for_tower <instance tag> &`
